feat: update to Volar 2.3
analogjs/language-tools pull request #2
Opened 2024-05-31 21:24 UTC by johnsoncodehk

Update Volar from 2.1 to 2.3 alpha. 2.3 is mainly API changes and should not cause breaking changes.

2024-06-01 16:35 UTC, brandonroberts requested changes

2024-06-01 16:35 UTC, brandonroberts commented on yarn.lock
Can we delete this file as we're already using pnpm?

2024-06-01 17:32 UTC, johnsoncodehk commented on yarn.lock
Done!

2024-06-09 00:35 UTC, johnsoncodehk commented
@brandonroberts The upgrade is complete!

2024-06-10 00:28 UTC, brandonroberts approved these changes

2024-06-10 00:29 UTC, merged

2024-06-10 00:29 UTC, brandonroberts commented
Thanks @johnsoncodehk!